steps:
    # Build an image.
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/cloudbuilder-unittest', '.']
    # Test the image.
    - name: 'gcr.io/gcp-runtimes/container-structure-test'
      args: ['test', '--image', 'eu.gcr.io/$PROJECT_ID/cloudbuilder-unittest', '--config', 'test_config.yaml']
    
# Push the image.
images: ['eu.gcr.io/$PROJECT_ID/cloudbuilder-unittest']